# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSecretKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=16, verbose_name='Secret Key')),
                ('lifetime', models.CharField(max_length=5, verbose_name='Lifetime')),
                ('status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MULTI', 'MULTI')], max_length=10, verbose_name='Lifetime')),
                ('levels', models.TextField(verbose_name='Levels')),
            ],
        ),
    ]
