# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsecretkey',
            name='status',
            field=models.CharField(choices=[('No active', 'No active'), ('Expired', 'Expired'), ('Active', 'Active')], max_length=10, verbose_name='Lifetime'),
        ),
    ]
