# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20171013_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=10, verbose_name='Level Name')),
                ('level_file', models.FileField(blank=True, upload_to='levels/', verbose_name='File script')),
            ],
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='status',
            field=models.CharField(choices=[('No active', 'No active'), ('Expired', 'Expired'), ('Active', 'Active')], max_length=10, verbose_name='Status'),
        ),
    ]
