# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20171013_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelfile',
            options={'ordering': ('level_name',)},
        ),
        migrations.AlterModelOptions(
            name='testsecretkey',
            options={'ordering': ('secret_key',)},
        ),
        migrations.AddField(
            model_name='levelfile',
            name='keys',
            field=models.ManyToManyField(to='index.TestSecretKey'),
        ),
        migrations.RemoveField(
            model_name='testsecretkey',
            name='levels',
        ),
        migrations.AddField(
            model_name='testsecretkey',
            name='levels',
            field=models.ManyToManyField(blank=True, to='index.LevelFile'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='secret_key',
            field=models.CharField(default='def', max_length=16, verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='status',
            field=models.CharField(choices=[('No active', 'No active'), ('Expired', 'Expired'), ('Active', 'Active')], default='Active', max_length=10, verbose_name='Status'),
        ),
    ]
