# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20171013_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelfile',
            name='keys',
            field=models.ManyToManyField(blank=True, to='index.TestSecretKey'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='lifetime',
            field=models.IntegerField(max_length=5, verbose_name='Lifetime'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='secret_key',
            field=models.CharField(default='AJ8x1aoPaKIgX1sSpIXh7WyEEqzqbgLD', max_length=32, verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='title',
            field=models.CharField(default='', max_length=35, verbose_name='Title'),
        ),
    ]
