# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20171013_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testsecretkey',
            name='id',
        ),
        migrations.AlterField(
            model_name='levelfile',
            name='level_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Level Name'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='lifetime',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Lifetime(days)'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='secret_key',
            field=models.CharField(default=index.models.gen_secret_key, max_length=32, primary_key=True, serialize=False, verbose_name='Secret Key'),
        ),
    ]
