# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20171013_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelfile',
            name='level_pub_date',
            field=models.DateTimeField(default=index.models.get_date_now),
        ),
        migrations.AddField(
            model_name='testsecretkey',
            name='key_pub_date',
            field=models.DateTimeField(default=index.models.get_date_now),
        ),
        migrations.AlterField(
            model_name='levelfile',
            name='level_name',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, verbose_name='Level Name'),
        ),
    ]
