# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 12:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20171013_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsecretkey',
            name='key_active_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='levelfile',
            name='level_name',
            field=models.CharField(help_text='max size: 35', max_length=35, primary_key=True, serialize=False, verbose_name='Level Name'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='lifetime',
            field=models.IntegerField(help_text='max size: 1000', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Lifetime(days)'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='title',
            field=models.CharField(default='', help_text='max size: 35', max_length=35, null=True, verbose_name='Title'),
        ),
    ]
