# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-22 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20171016_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='max size: 35', max_length=35, verbose_name='Group Name')),
            ],
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='key_active_date',
            field=models.DateTimeField(null=True, verbose_name='key activation date'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='key_pub_date',
            field=models.DateTimeField(default=index.models.get_date_now, verbose_name='key release date'),
        ),
        migrations.AlterField(
            model_name='testsecretkey',
            name='status',
            field=models.CharField(choices=[('No active', 'No active'), ('Expired', 'Expired'), ('Active', 'Active')], default='No active', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='keygroup',
            name='keys',
            field=models.ManyToManyField(blank=True, to='index.TestSecretKey'),
        ),
        migrations.AddField(
            model_name='testsecretkey',
            name='groups',
            field=models.ManyToManyField(blank=True, to='index.KeyGroup'),
        ),
    ]
